### ISSUE TITLE
Помощь

### ISSUE THREAD

**Issue by salarik** [muxanick/BDORUS#2]
Опишите принцип как вы переводите и как следите за изменениями в версиях(если меняется что то в текстах). Рад буду помочь.

**Comment by muxanick** [comment]
Перевод идет на сайте bdorus.oneskyapp.com
Там как раз и обновление исходников происходит, и строки опять на перевод уходят

**Comment by salarik** [comment]
Спасибо за быстрый ответ. Печально что там, на работе блокировки не позволят там полноценно работать. Придется только с дома.
